// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class VaccinationConsentForm
{
    public int VaccinationConsentFormId { get; set; }

    public int? ParentId { get; set; }

    public int? StudentId { get; set; }

    public int? VaccineCampaignId { get; set; }

    public DateTime? SubmissionTime { get; set; }

    public string Notes { get; set; }

    public bool? IsApproved { get; set; }

    public virtual User Parent { get; set; }

    public virtual StudentsHoaLq Student { get; set; }

    public virtual ICollection<VaccinationRecord> VaccinationRecords { get; set; } = new List<VaccinationRecord>();

    public virtual VaccineCampaignsTinHt VaccineCampaign { get; set; }
}