// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class VaccinationConsentFormsTinHt
{
    public int VaccinationConsentFormTinHtid { get; set; }

    public int? ParentId { get; set; }

    public int? StudentId { get; set; }

    public int? VaccineCampaignId { get; set; }

    public DateTime? SubmissionTime { get; set; }

    public string Notes { get; set; }

    public bool? IsApproved { get; set; }
}